### ISSUE TITLE
1º Placeholder isn't working. 2º Limit of enchants can't be modify

### ISSUE THREAD

**Issue by TheExotik** [Puyodead1/EnchantCrystals#7]
1º issue:
The placeholders %ENCHANTMENT_LEVEL_MAX% isn't working, idk why, but when i run /ecr give [player] [enchant] 8 
say isn't possible.... between 1 and %ENCHANTMENT_LEVEL_MAX%

2º issue:
I've trying to found some way to modify/change the level max of the enchantments but using this crystal, i can't
i've add other plugin to edit the level max of enchantments, and works, but if i try enchant the item with crystal isn't work...

purpur-1171
minecraft 1.16.5
java 16

**Comment by Puyodead1** [comment]
Thank you for the report, I will look into these issues when I get a chance. What plugin are you using the change the max level of enchantments so that I can test and try to add compatibility with?

**Comment by TheExotik** [comment]
i was using UberEnchant and EnhancedEchants

**Comment by Puyodead1** [comment]
Issue 1: The reason is because the correct command is `/ecr give <enchant> [level] [amount] [player]`

Issue 2: The plugin only supports vanilla enchantments. I looked at the plugins you mentioned but they don't seem to be open source and/or have a developer API that I could use to add compatibility.
